### PR TITLE
add some snippets

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by freebroccolo** [comment]
@jonsterling You might want to take a look at the `onEnterRules` too. See [here](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/extension.ts#L11). It can be a bit fiddly to get the rules right but it works pretty nicely once you do.

**Comment by freebroccolo** [comment]
Btw, feel free to add more snippets. I realized maybe I merged this too quickly if you're still working on them.

**Comment by jonsterling** [comment]
@freebroccolo ooo, `onEnterRules` looks cool. thanks for the tip!

**Comment by jonsterling** [comment]
@freebroccolo BTW, do you know if there's a way to give snippets higher "precedence" in the intellisense listing? Right now, I get completions for things like `signature` before the actual snippet.

**Comment by freebroccolo** [comment]
@jonsterling there is a setting `editor.snippetSuggestions` that I think allows you to control this. The available settings for it are `[ "bottom", "inline", "none", "top" ]` (you can pull up that list with ctrl+space which activates the suggestions for the setting value). If you change it to "top" I think it will do what you want.

There are some other settings related to suggestions that you can also find like in the screenshot:

suggestions

**Pull request merged**
